### ISSUE TITLE
Feature idea: Add some example words

### ISSUE THREAD

**Issue by lag00n** [tteeoo/neotype#1]
That can be really useful

**Comment by tteeoo** [comment]
I'm not sure what you mean. Could you please elaborate?

**Comment by lag00n** [comment]
Adding some built-in words in the words file would be good :)

**Comment by tteeoo** [comment]
Ah, I think I know what happened. There is a file in the repository with 1000 English words, but the original install instructions I had in the readme didn't actually work. It's just a matter of copying the file `share/words.txt` to `~/.local/share/neotype/`.

**Comment by lag00n** [comment]
Nah, it was a misreading by my part...
I apologize for the inconvenience.

**Comment by tteeoo** [comment]
No worries, I'm glad to help by clarifying for you!
